### ISSUE TITLE
Change default CORS allowed headers and make it customizable

### ISSUE THREAD

**Issue by guillaumejacquart** [flagship-io/decision-api#6]
The default `Access-Control-Allow-Headers` values are too limited. It would be nice to have the same allowed headers as the cloud API: `Content-Type,Authorization,X-Api-Key,X-Sdk-Client,X-Sdk-Version,X-Pop`
And it would also be nice to make those allowed headers customizable through config and environment variable

**Comment by Chadiii** [comment]
You can find the feature in a pull request : https://github.com/flagship-io/decision-api/pull/7 , thanks for the feedback
